version: "v3.0"
name: My first pipeline touch
semaphore_image: standard
blocks:
  - name: "Stage 1 -- create cache"
    build:
      prologue:
        commands:
          - checkout && cd $SEMAPHORE_GIT_DIR
      epilogue:
        commands:
          - echo "Yay job finished"
          - echo $SEMAPHORE_JOB_RESULT
      env_vars:
        - name: SEMAPHORE_CACHE_USERNAME
          value: "u180539"
        - name: SEMAPHORE_CACHE_URL
          value: "u180539.your-storagebox.de"
        - name: SEMAPHORE_CACHE_URL
          value: "u180539.your-storagebox.de"
        - name: SSH_PRIVATE_KEY_PATH
          value: .semaphore/hetzner_storage_bx20

      jobs:
      - name: Install bundle 1
        commands:
          - echo "v1-git" > /tmp/git-key
          - cache restore --key Gemfile.lock
          - cache restore --key /tmp/git-key
          - bundle install --path=vendor/bundle
          - cache store --key Gemfile.lock --path vendor
          - cache store --key /tmp/git-key --path $SEMAPHORE_GIT_DIR/.git

  - name: "Stage 2 -- reuse cache"
    build:
      env_vars:
        - name: SEMAPHORE_CACHE_USERNAME
          value: "u180539"
        - name: SEMAPHORE_CACHE_URL
          value: "u180539.your-storagebox.de"
        - name: SEMAPHORE_CACHE_URL
          value: "u180539.your-storagebox.de"
        - name: SSH_PRIVATE_KEY_PATH
          value: .semaphore/hetzner_storage_bx20

      jobs:
      - name: Install bundle 2
        commands:
          - checkout && cd $SEMAPHORE_GIT_DIR
          - mv .semaphore/hetzner_storage_bx20 /tmp/key
          - export SSH_PRIVATE_KEY_PATH=/tmp/key
          - cd
          - rm -rf $SEMAPHORE_GIT_DIR
          - echo "v1-git" > /tmp/git-key
          - cache restore --key /tmp/git-key
          - cd $SEMAPHORE_GIT_DIR
          - cache restore --key Gemfile.lock
          - bundle install --path=vendor/bundle
          - cache store --key Gemfile.lock --path vendor
